# Generated by Django 5.2.7 on 2026-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0019_fix_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelinfo',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('wavespeedai', 'Wavespeed AI'), ('google', 'Google'), ('deepseek', 'deepseek'), ('groq', 'Groq')], help_text='Model provider or vendor.', max_length=50),
        ),
    ]
