# Generated by Django 5.2.7 on 2026-02-15 20:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_fix_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google AI'), ('anthropic', 'Anthropic'), ('wavespeed', 'WaveSpeed AI'), ('leonardo', 'Leonardo AI'), ('fal', 'FAL AI'), ('deepseek', 'DeepSeek'), ('stability', 'Stability AI'), ('replicate', 'Replicate')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('api_key', models.TextField(blank=True, help_text='Encrypted API key')),
                ('api_base_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority = preferred provider')),
                ('rate_limit', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('timeout_seconds', models.IntegerField(default=60)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Provider Configuration',
                'verbose_name_plural': 'API Provider Configurations',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(db_index=True, default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('secret_key', models.TextField(blank=True, help_text='Webhook secret for signature verification')),
                ('events', models.JSONField(default=list, help_text='List of events to trigger this webhook')),
                ('is_active', models.BooleanField(default=True)),
                ('retry_count', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Configuration',
                'verbose_name_plural': 'Webhook Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='accounts_sy_level_679b5a_idx'), models.Index(fields=['category', 'created_at'], name='accounts_sy_categor_36ccf3_idx'), models.Index(fields=['user', 'created_at'], name='accounts_sy_user_id_a07906_idx')],
            },
        ),
    ]
