"""
Django settings for AIModelBackend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from decouple import config, Csv
import os

# Environment detection
ENVIRONMENT = config('ENVIRONMENT', default='development')

BASE_URL = config('BASE_URL', default='http://localhost:8000')

AUTH_USER_MODEL = 'accounts.CustomUser'

#for google authentication
# You can set multiple client IDs based on your Expo config.
GOOGLE_CLIENT_IDS = [
    os.environ.get("EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID", "placeholder-web.apps.googleusercontent.com"),
    os.environ.get("EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID", "placeholder-ios.apps.googleusercontent.com"),
    os.environ.get("EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID", "placeholder-android.apps.googleusercontent.com"),
]




#for google pay billing 

GOOGLE_SERVICE_ACCOUNT_FILE = os.path.join(BASE_DIR, "google_service_account.json")
GOOGLE_PACKAGE_NAME = "com.aimodel.mobile" # your app's actual package name

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_default_secret = 'dev-only-insecure-key-change-before-production'
SECRET_KEY = config('SECRET_KEY', default=_default_secret if ENVIRONMENT != 'production' else '')

if ENVIRONMENT == 'production' and SECRET_KEY in ('', _default_secret):
    raise ValueError('SECRET_KEY must be set to a secure value in production.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Allowed hosts configuration
# For production: set ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com in .env
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='127.0.0.1,localhost,10.10.13.75,10.10.13.60',
    cast=Csv()
)

# Add development hosts only when not in production
if ENVIRONMENT != 'production':
    ALLOWED_HOSTS += [
        'overrigged-botanically-lila.ngrok-free.dev',
        '4867888fdea6.ngrok-free.app',
        '7817aa52e070.ngrok-free.app',
        'aeronautic-unjumpable-nahla.ngrok-free.dev',
        '10.224.57.121',
        '172.18.133.153',
        '10.133.245.121',
        '192.168.1.17',
        '192.168.1.16',
        '10.84.46.121',
    ]

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:8000,http://localhost:3000,http://127.0.0.1:8000,http://127.0.0.1:3000',
    cast=Csv(),
)

if ENVIRONMENT != 'production':
    CSRF_TRUSTED_ORIGINS += [
        'https://overrigged-botanically-lila.ngrok-free.dev',
        'https://aeronautic-unjumpable-nahla.ngrok-free.dev',
        'https://4867888fdea6.ngrok-free.app',
    ]

# Proxy settings for ngrok/reverse proxy
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_SECURE = ENVIRONMENT == 'production'
CSRF_COOKIE_SECURE = ENVIRONMENT == 'production'
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=ENVIRONMENT == 'production', cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000 if ENVIRONMENT == 'production' else 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = ENVIRONMENT == 'production'
SECURE_HSTS_PRELOAD = ENVIRONMENT == 'production'

# Application definition
APPEND_SLASH = False
INSTALLED_APPS = [
    "daphne",
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'ai_model.apps.AiModelConfig',
    'accounts',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'channels',
    'plan',
    'invoices',
    'ads_rewards',
    'django_filters',
    'drf_spectacular',
    

]

#unfold settings

UNFOLD = {
    "SITE_TITLE": "Z99 Admin",
    "SITE_HEADER": "Z99 Administration",
    "SITE_URL": "/",
    "SITE_SYMBOL": "dashboard",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    

    "SIDEBAR": {   # FIXED KEY
        "show_icons": True,
        "show_search": True,
    },
}
SORA_HIGH_RES_ENABLED = True

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

# Redis/Celery configuration
# For local dev: redis://127.0.0.1:6379/0
# For Docker: redis://redis:6379/0
REDIS_URL = config('REDIS_URL', default='redis://127.0.0.1:6379/0')
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=REDIS_URL)
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=REDIS_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# CELERY_TASK_ALWAYS_EAGER = True
#stripe 

STRIPE_SECRET_KEY =config("STRIPE_SECRET_KEY")
WEBHOOK_SECRET=config("WEBHOOK_SECRET_KEY")
AI_WEBHOOK_SECRET = config("AI_WEBHOOK_SECRET", default="")
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# settings.py

# ROTATE_REFRESH_TOKENS = True
# BLACKLIST_AFTER_ROTATION = True

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
      # 'users.authentication.CookieJWTAuthentication',
    ),
    # Secure-by-default: endpoints require auth unless explicitly marked public.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'UNICODE_JSON': True,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # Custom exception handler for consistent error responses
    'EXCEPTION_HANDLER': 'AIModelBackend.exceptions.custom_exception_handler',
    
    # Throttling - Rate limiting using custom classes
    'DEFAULT_THROTTLE_CLASSES': [
        'AIModelBackend.throttling.BurstRateThrottle',
        'AIModelBackend.throttling.SustainedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',      # Anonymous users: 100 requests/hour
        'user': '1000/hour',     # Authenticated users: 1000 requests/hour
        'burst_anon': '20/min',  # Anonymous burst: 20/minute
        'burst_user': '60/min',  # Authenticated burst: 60/minute
        'sustained_anon': '100/hour',  # Anonymous sustained: 100/hour
        'sustained_user': '1000/hour', # Authenticated sustained: 1000/hour
        'ai_generation': '30/hour',    # AI generation: 30/hour
    },
    
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 10,
    # 'DEFAULT_FILTER_BACKENDS': [
    #     'rest_framework.filters.SearchFilter',
    #     'rest_framework.filters.OrderingFilter',
    #     'django_filters.rest_framework.DjangoFilterBackend',
    # ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'My Backend API',
    'DESCRIPTION': 'API documentation for my project',
    'VERSION': '1.0.0',
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=480),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),

}

ROOT_URLCONF = 'AIModelBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AIModelBackend.wsgi.application'
ASGI_APPLICATION = 'AIModelBackend.asgi.application'
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],  # or your Redis server
#         },
#     },
# }
if ENVIRONMENT == 'production':
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration - supports SQLite (dev) and PostgreSQL (production)
DATABASE_ENGINE = config('DATABASE_ENGINE', default='sqlite')

if DATABASE_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='aimodel_db'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATIC_ROOT = BASE_DIR / "staticfiles"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
# https://github.com/adamchainz/django-cors-headers
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=False, cast=bool)

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:8080,http://localhost:8081,http://127.0.0.1:3000,http://127.0.0.1:8081',
    cast=Csv(),
)

if CORS_ALLOW_ALL_ORIGINS and ENVIRONMENT == 'production':
    raise ValueError('CORS_ALLOW_ALL_ORIGINS must be false in production.')

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',
]

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'structured': {
            '()': 'AIModelBackend.logging_config.StructuredLogFormatter',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'structured_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'structured.log',
            'formatter': 'structured',
        },
        'websocket_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'websocket.log',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'mail_admins'],
            'level': 'WARNING',
            'propagate': False,
        },
        'plan': {
            'handlers': ['console', 'file', 'structured_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai_model': {
            'handlers': ['console', 'file', 'structured_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'websocket': {
            'handlers': ['console', 'websocket_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'file', 'structured_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'invoices': {
            'handlers': ['console', 'file', 'structured_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'ads_rewards': {
            'handlers': ['console', 'file', 'structured_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)
