# Generated by Django 5.2.7 on 2026-02-15 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_subscriptionmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='planmodel',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='planmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='plan_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='duration_type',
            field=models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='expire_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active'), ('expired', 'expired')], default='active', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='subscriptionmodel',
            index=models.Index(fields=['user', 'status'], name='plan_subscr_user_id_ce99b7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionmodel',
            index=models.Index(fields=['expire_date', 'status'], name='plan_subscr_expire__928acc_idx'),
        ),
    ]
