import React, { useState } from 'react';
import { 
  View, Text, StyleSheet, TouchableOpacity, 
  ScrollView, Alert, ActivityIndicator 
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as DocumentPicker from 'expo-document-picker';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing, borderRadius } from '../theme';
import GlassCard from '../components/GlassCard';
import GradientButton from '../components/GradientButton';
import { useCredits, useDrawer } from '../context';

export default function SpeechToTextScreen() {
  const insets = useSafeAreaInsets();
  const { openDrawer } = useDrawer();
  const { credits, deductCredits } = useCredits();

  const [mode, setMode] = useState<'record' | 'upload'>('record');
  const [isRecording, setIsRecording] = useState(false);
  const [selectedFile, setSelectedFile] = useState<any>(null);
  const [isTranscribing, setIsTranscribing] = useState(false);
  const [transcript, setTranscript] = useState<string | null>(null);

  const toggleRecording = () => {
    if (isRecording) {
      // Stop recording
      setIsRecording(false);
      handleTranscribe();
    } else {
      setIsRecording(true);
      setTranscript(null);
    }
  };

  const pickAudio = async () => {
    try {
      const result = await DocumentPicker.getDocumentAsync({
        type: ['audio/*'],
        copyToCacheDirectory: true,
      });

      if (!result.canceled && result.assets && result.assets.length > 0) {
        setSelectedFile(result.assets[0]);
        setTranscript(null);
      }
    } catch (err) {
      console.log('Error picking audio', err);
    }
  };

  const handleTranscribe = () => {
    if (!credits || credits.credits < 15) {
      Alert.alert('Insufficient Credits', 'Transcription costs 15 coins.');
      return;
    }
    
    setIsTranscribing(true);
    
    // Simulate API call
    setTimeout(() => {
      deductCredits(15, "Speech to text generation");
      setTranscript("This is a highly accurate transcribed text generated by our AI model. It captures every nuance of the speech seamlessly and formats it perfectly into readable text. You can copy or share this text as needed.");
      setIsTranscribing(false);
    }, 3000);
  };

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity 
          style={styles.headerButton} 
          onPress={openDrawer}
          accessibilityRole="button"
          accessibilityLabel="Open Menu"
        >
          <Ionicons name="menu-outline" size={24} color={colors.textSecondary} />
        </TouchableOpacity>
        
        <Text style={styles.headerTitle}>Speech to Text</Text>
        
        <View style={styles.headerButton}>
          <View style={styles.coinBadge}>
            <Text style={styles.coinIcon}>{"\uD83E\uDE99"}</Text>
              <Text style={styles.coinBadgeText}>🪙 {credits?.credits || 0}</Text>
          
      </View>
      </View>
      </View>
      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        
        {/* Toggle Mode */}
        <View style={styles.segmentedControl}>
          <TouchableOpacity 
            style={[styles.segment, mode === 'record' && styles.segmentActive]}
            onPress={() => setMode('record')}
          >
            <Ionicons name="mic-outline" size={18} color={mode === 'record' ? colors.white : colors.textSecondary} />
            <Text style={[styles.segmentText, mode === 'record' && styles.segmentTextActive]}>Dictate</Text>
          </TouchableOpacity>
          <TouchableOpacity 
            style={[styles.segment, mode === 'upload' && styles.segmentActive]}
            onPress={() => setMode('upload')}
          >
            <Ionicons name="cloud-upload-outline" size={18} color={mode === 'upload' ? colors.white : colors.textSecondary} />
            <Text style={[styles.segmentText, mode === 'upload' && styles.segmentTextActive]}>Upload File</Text>
          </TouchableOpacity>
        </View>

        {/* Input Area */}
        <View style={styles.inputSection}>
          {mode === 'record' ? (
            <View style={styles.recordContainer}>
              <TouchableOpacity 
                style={[styles.recordButton, isRecording && styles.recordButtonActive]} 
                onPress={toggleRecording}
                activeOpacity={0.8}
              >
                <View style={[styles.recordInner, isRecording && styles.recordInnerActive]}>
                  <Ionicons name={isRecording ? "stop" : "mic"} size={48} color={colors.white} />
                </View>
              </TouchableOpacity>
              <Text style={styles.recordStatusText}>
                {isRecording ? "Listening... Tap to stop" : "Tap to start speaking"}
              </Text>
            </View>
          ) : (
            <View style={styles.uploadContainer}>
              {!selectedFile ? (
                <TouchableOpacity style={styles.dropzone} onPress={pickAudio}>
                  <View style={styles.iconCircle}>
                    <Ionicons name="document-text" size={32} color={colors.primary} />
                  </View>
                  <Text style={styles.dropzoneTitle}>Tap to browse files</Text>
                  <Text style={styles.dropzoneSub}>Supports MP3, WAV, M4A up to 50MB</Text>
                </TouchableOpacity>
              ) : (
                <GlassCard style={styles.fileCard}>
                  <Ionicons name="musical-notes" size={24} color={colors.primary} />
                  <View style={styles.fileDetails}>
                    <Text style={styles.fileName} numberOfLines={1}>{selectedFile.name}</Text>
                    <Text style={styles.fileSize}>{(selectedFile.size / 1024 / 1024).toFixed(2)} MB</Text>
                  </View>
                  <TouchableOpacity onPress={() => setSelectedFile(null)}>
                    <Ionicons name="close-circle" size={24} color={colors.error} />
                  </TouchableOpacity>
                </GlassCard>
              )}
            </View>
          )}
        </View>

        {/* Action Button for Upload Mode manually triggering transcribe */}
        {mode === 'upload' && selectedFile && (
           <View style={{ marginTop: spacing.xl }}>
             <GradientButton
               title={isTranscribing ? "Transcribing..." : "Transcribe File"}
               onPress={handleTranscribe}
               disabled={isTranscribing}
               icon={isTranscribing ? <ActivityIndicator color={colors.white} /> : <Ionicons name="document-text" size={20} color={colors.white} />}
               badge={"\uD83E\uDE99 15 Credits"}
             />
           </View>
        )}
        
        {isTranscribing && mode === 'record' && (
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="large" color={colors.primary} />
            <Text style={styles.loadingText}>Processing speech...</Text>
          </View>
        )}

        {/* Output Area */}
        {transcript && (
          <View style={styles.resultContainer}>
            <Text style={styles.sectionTitle}>Transcript</Text>
            <GlassCard style={styles.transcriptCard}>
              <Text style={styles.transcriptText}>{transcript}</Text>
              
              <View style={styles.transcriptActions}>
                <TouchableOpacity style={styles.actionBtn}>
                  <Ionicons name="copy-outline" size={18} color={colors.primary} />
                  <Text style={styles.actionBtnText}>Copy</Text>
                </TouchableOpacity>
                <TouchableOpacity style={styles.actionBtn}>
                  <Ionicons name="share-social-outline" size={18} color={colors.primary} />
                  <Text style={styles.actionBtnText}>Share</Text>
                </TouchableOpacity>
              </View>
            </GlassCard>
          </View>
        )}

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.background,
  },
  headerButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  scrollContent: { gap: spacing.lg, padding: spacing.lg, paddingBottom: 100 },
  
  segmentedControl: {
    flexDirection: 'row', backgroundColor: 'transparent',
    borderRadius: 24, padding: spacing.xs, marginBottom: spacing.xl,
    borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)',
  },
  segment: {
    flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    paddingVertical: spacing.sm, borderRadius: 20,
  },
  segmentActive: { backgroundColor: 'rgba(16, 163, 127, 0.12)', borderColor: 'rgba(16, 163, 127, 0.3)', borderWidth: 1 },
  segmentText: { marginLeft: spacing.xs, fontSize: 13, fontWeight: '600', color: colors.textSecondary },
segmentTextActive: { color: '#10a37f' },
  inputSection: { minHeight: 250, justifyContent: 'center' },
  
  recordContainer: { alignItems: 'center' },
  recordButton: {
    width: 140, height: 140, borderRadius: 70,
    backgroundColor: colors.primary + '20',
    alignItems: 'center', justifyContent: 'center',
  },
  recordButtonActive: { backgroundColor: colors.error + '30' },
  recordInner: {
    width: 100, height: 100, borderRadius: 50,
    backgroundColor: colors.primary,
    alignItems: 'center', justifyContent: 'center',
    shadowColor: colors.primary, shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4, shadowRadius: 16, elevation: 8,
  },
  recordInnerActive: {
    backgroundColor: colors.error, shadowColor: colors.error, borderRadius: 30, // square morph effect
  },
  recordStatusText: { marginTop: spacing.xl, fontSize: 16, fontWeight: '500', color: colors.textSecondary, letterSpacing: 0.5 },
  
  uploadContainer: {},
  dropzone: {
    borderWidth: 2, borderColor: colors.border, borderStyle: 'dashed',
    borderRadius: borderRadius.xl, padding: spacing.xl,
    alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface + '40',
  },
  iconCircle: {
    width: 64, height: 64, borderRadius: 32, backgroundColor: colors.primary + '10',
    alignItems: 'center', justifyContent: 'center', marginBottom: spacing.md,
  },
  dropzoneTitle: { fontSize: 16, fontWeight: '600', color: colors.textPrimary },
  dropzoneSub: { fontSize: 13, color: colors.textSecondary, marginTop: spacing.xs },
  
  fileCard: { flexDirection: 'row', alignItems: 'center', padding: spacing.md },
  fileDetails: { flex: 1, marginLeft: spacing.md },
  fileName: { fontSize: 14, fontWeight: '600', color: colors.textPrimary },
  fileSize: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
  
  loadingContainer: { alignItems: 'center', marginTop: spacing.xl },
  loadingText: { marginTop: spacing.md, color: colors.primary, fontWeight: '500' },
  
  resultContainer: { marginTop: spacing.xl },
  sectionTitle: { fontSize: 12, fontWeight: '700', color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: spacing.sm, marginLeft: spacing.xs },
  transcriptCard: { padding: spacing.lg, paddingBottom: spacing.sm },
  transcriptText: { fontSize: 16, color: colors.textPrimary, lineHeight: 26, marginBottom: spacing.lg },
  transcriptActions: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: colors.border, paddingTop: spacing.md, gap: spacing.lg },
  actionBtn: { flexDirection: 'row', alignItems: 'center' },
  actionBtnText: { marginLeft: spacing.sm, fontSize: 14, fontWeight: '600', color: colors.primary },
    coinBadge: {
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  coinBadgeText: {
    color: '#F59E0B',
    fontSize: 14,
    fontWeight: 'bold',
  },
  coinIcon: { fontSize: 12 }
});
